
package com.soen487.t05.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MissingName", targetNamespace = "http://www.soen487.com/t05")
public class MissingName_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MissingName faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MissingName_Exception(String message, MissingName faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MissingName_Exception(String message, MissingName faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.soen487.t05.client.MissingName
     */
    public MissingName getFaultInfo() {
        return faultInfo;
    }

}
