
package com.soen487.t05.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Welcome", targetNamespace = "http://www.soen487.com/t05")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Welcome {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     * @throws MissingName_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWelcomeMsg", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.GetWelcomeMsg")
    @ResponseWrapper(localName = "getWelcomeMsgResponse", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.GetWelcomeMsgResponse")
    @Action(input = "http://www.soen487.com/t05/Welcome/getWelcomeMsgRequest", output = "http://www.soen487.com/t05/Welcome/getWelcomeMsgResponse", fault = {
        @FaultAction(className = MissingName_Exception.class, value = "http://www.soen487.com/t05/Welcome/getWelcomeMsg/Fault/MissingName")
    })
    public String getWelcomeMsg(
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws MissingName_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.soen487.t05.client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonArray", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.GetPersonArray")
    @ResponseWrapper(localName = "getPersonArrayResponse", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.GetPersonArrayResponse")
    @Action(input = "http://www.soen487.com/t05/Welcome/getPersonArrayRequest", output = "http://www.soen487.com/t05/Welcome/getPersonArrayResponse")
    public List<Person> getPersonArray();

    /**
     * 
     * @param file
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "uploadImageV2", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.UploadImageV2")
    @ResponseWrapper(localName = "uploadImageV2Response", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.UploadImageV2Response")
    @Action(input = "http://www.soen487.com/t05/Welcome/uploadImageV2Request", output = "http://www.soen487.com/t05/Welcome/uploadImageV2Response", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://www.soen487.com/t05/Welcome/uploadImageV2/Fault/IOException")
    })
    public void uploadImageV2(
        @WebParam(name = "file", targetNamespace = "")
        byte[] file)
        throws IOException_Exception
    ;

    /**
     * 
     * @param file
     * @param mime
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "uploadImage", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.UploadImage")
    @ResponseWrapper(localName = "uploadImageResponse", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.UploadImageResponse")
    @Action(input = "http://www.soen487.com/t05/Welcome/uploadImageRequest", output = "http://www.soen487.com/t05/Welcome/uploadImageResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://www.soen487.com/t05/Welcome/uploadImage/Fault/IOException")
    })
    public void uploadImage(
        @WebParam(name = "file", targetNamespace = "")
        byte[] file,
        @WebParam(name = "mime", targetNamespace = "")
        String mime)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns byte[]
     * @throws SOAPException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadImage", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.DownloadImage")
    @ResponseWrapper(localName = "downloadImageResponse", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.DownloadImageResponse")
    @Action(input = "http://www.soen487.com/t05/Welcome/downloadImageRequest", output = "http://www.soen487.com/t05/Welcome/downloadImageResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://www.soen487.com/t05/Welcome/downloadImage/Fault/SOAPException"),
        @FaultAction(className = IOException_Exception.class, value = "http://www.soen487.com/t05/Welcome/downloadImage/Fault/IOException")
    })
    public byte[] downloadImage()
        throws IOException_Exception, SOAPException_Exception
    ;

    /**
     * 
     * @param name
     * @param id
     * @param age
     * @throws MissingName_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://www.soen487.com/t05", className = "com.soen487.t05.client.AddPersonResponse")
    @Action(input = "http://www.soen487.com/t05/Welcome/addPersonRequest", output = "http://www.soen487.com/t05/Welcome/addPersonResponse", fault = {
        @FaultAction(className = MissingName_Exception.class, value = "http://www.soen487.com/t05/Welcome/addPerson/Fault/MissingName")
    })
    public void addPerson(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        int age)
        throws MissingName_Exception
    ;

}
